spring:
 application:
    name: hospitalapp
  
 datasource:
#  url: jdbc:postgresql://localhost:5432/hospitalmanagement_db
#  username: postgres
#  password: Admin@123
#  driver-class-name : org.postgresql.Driver

  # Configuring cloud database credentials
  url: jdbc:postgresql://hospital-management.ccv8qy8qsabn.ap-south-1.rds.amazonaws.com:5432/hospitalmanagement_db
  username: postgres
  password: qwerty12345
  driver-class-name : org.postgresql.Driver
 
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true  
    
    
server:
  port: 9091
  
#Client URL
auth:
 url: http://localhost:9090/authapp
 name: authapp
 
#Circuit Breaker And Retry
resilience4j:
 retry:
  retry-aspect-order: 2
  instances:
   hospitalRetry:
    max-attempts: 3
    wait-duration: 5s
     
 circuitbreaker:
  circuit-breaker-aspect-order: 1
  instances:
   hospitalCircuitBreaker:
    wait-duration-in-open-state: 1m
    permitted-number-of-calls-in-half-open-state: 3
    sliding-window-type: count-based
    sliding-window-size: 5
    minimum-number-of-calls: 5
    failure-rate-threshold: 60
    
# AWS Configuration

aws:
 access-key: AKIAUV66CJ23OJ73ZNUB
 secret-key: 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
 topic-arn: arn:aws:sns:ap-south-1:322051395254:HM_Notification 
 
  
