spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/hospitalmanagement_db
  username: postgres
  password: Admin@123
  driver-class-name : org.postgresql.Driver
  
  # Configuring cloud database credentials
#  url: jdbc:postgresql://hospital-management.ccv8qy8qsabn.ap-south-1.rds.amazonaws.com:5432/hospitalmanagement_db
#  username: postgres
#  password: qwerty12345
#  driver-class-name : org.postgresql.Driver
  
 
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true
  
 application:
  name: authapp
        
server:
  port: 9090
    
jwt:
 secret: sampletest 
 