spring:
 application:
    name: insuranceapp
  
 datasource:
  url: jdbc:postgresql://localhost:5432/hospitalmanagement_db
  username: postgres
  password: Admin@123
  driver-class-name : org.postgresql.Driver
 
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true  
    
    
server:
  port: 9092
  
#Client URL
auth:
 url: http://localhost:9090/authapp
 name: authapp
 
hospital:
 url: http://localhost:9091/hospitalapp
 name: hospitalapp 

