spring:
 application:
    name: insuranceapp
  
 datasource:
  url: jdbc:postgresql://localhost:5432/hospitalmanagement_db
  username: postgres
  password: Admin@123
  driver-class-name : org.postgresql.Driver
 
 jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
   ddl-auto: update
  show-sql: true  
    
    
server:
  port: 9092
  
#Client URL
auth:
 url: http://localhost:9090/authapp
 name: authapp
 
hospital:
 url: http://localhost:9091/hospitalapp
 name: hospitalapp 
 
#Circuit Breaker And Retry
resilience4j:
 retry:
  retry-aspect-order: 2
  instances:
   insuranceRetry:
    max-attempts: 3
    wait-duration: 5s
     
 circuitbreaker:
  circuit-breaker-aspect-order: 1
  instances:
   insuranceCircuitBreaker:
    wait-duration-in-open-state: 1m
    permitted-number-of-calls-in-half-open-state: 3
    sliding-window-type: count-based
    sliding-window-size: 5
    minimum-number-of-calls: 5
    failure-rate-threshold: 60
    
    
#Cache cleanup time
caching:
 spring:
  hmTTL: 60000     
    
 

