-- Trigger
CREATE TRIGGER CALCULATE_SUM_FOR_BILLS_TRIGGER_AFTER_INSERT
AFTER INSERT 
ON HOSPITAL.BILL_TABLE
FOR EACH ROW
EXECUTE PROCEDURE HOSPITAL.CALCULATE_SUM_FOR_BILLS_TRIGGER_AFTER_INSERT_FUNCTION();

-- Trigger Function

CREATE OR REPLACE FUNCTION HOSPITAL.CALCULATE_SUM_FOR_BILLS_TRIGGER_AFTER_INSERT_FUNCTION()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
	AS
$$
BEGIN
		UPDATE HOSPITAL.BILL_TABLE
		SET TOTAL_AMOUNT_OF_BILL = (CONSULTATION_FEE + HOSPITALIZATION_FEE + PHARMACY_FEE);		
		RETURN NEW;

END;
$$

-- DROP_TRIGGER
DROP TRIGGER CALCULATE_SUM_FOR_BILLS_TRIGGER_AFTER_INSERT
ON HOSPITAL.BILL_TABLE;

DROP FUNCTION HOSPITAL.CALCULATE_SUM_FOR_BILLS_TRIGGER_AFTER_INSERT_FUNCTION;


